# ============================================================
# Author: Tarun Vangari (tarun.vangari@gmail.com)
# ADLC-Agent-Kit | Team Panchayat -- Console Authorization
# Run ONCE before first use: .\authorize-agents.ps1
# ============================================================
#
# What this script does:
#  1. Validates / sets your ANTHROPIC_API_KEY
#  2. Writes .env file for Docker mode
#  3. Writes .claude\settings.json with all tool permissions pre-approved
#  4. Verifies 'claude' CLI is installed and authenticated
#  5. Trusts this workspace directory so agents never prompt for permissions
#  6. Confirms readiness of all 7 prompt files
# ============================================================

$ROOT = $PSScriptRoot
Set-Location $ROOT

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  Team Panchayat -- Console Authorization Setup" -ForegroundColor Cyan
Write-Host "  Kit root: $ROOT" -ForegroundColor Gray
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# ---- Step 1: Check claude CLI -------------------------------------------------
Write-Host "[1/6] Checking 'claude' CLI installation..." -ForegroundColor Yellow
$claudePath = (Get-Command claude -ErrorAction SilentlyContinue)
if (-not $claudePath) {
    Write-Host ""
    Write-Host "  ERROR: 'claude' command not found." -ForegroundColor Red
    Write-Host "  Install it first:" -ForegroundColor White
    Write-Host "    npm install -g @anthropic-ai/claude-code" -ForegroundColor Cyan
    Write-Host ""
    Read-Host "Press Enter to exit"
    exit 1
}
Write-Host "  OK -- claude found at: $($claudePath.Source)" -ForegroundColor Green

# ---- Step 2: ANTHROPIC_API_KEY ------------------------------------------------
Write-Host ""
Write-Host "[2/6] Checking ANTHROPIC_API_KEY..." -ForegroundColor Yellow

$apiKey = $env:ANTHROPIC_API_KEY
if (-not $apiKey -or $apiKey.Length -lt 10) {
    # Try reading from existing .env file
    $envFile = Join-Path $ROOT ".env"
    if (Test-Path $envFile) {
        $line = Get-Content $envFile | Where-Object { $_ -match "^ANTHROPIC_API_KEY=" }
        if ($line) {
            $apiKey = $line -replace "^ANTHROPIC_API_KEY=", "" -replace '"', '' -replace "'", ''
            Write-Host "  Found API key in .env file." -ForegroundColor DarkGray
        }
    }
}

if (-not $apiKey -or $apiKey.Length -lt 10) {
    Write-Host ""
    Write-Host "  No API key found in environment or .env file." -ForegroundColor Yellow
    Write-Host "  Get your key from: https://console.anthropic.com/" -ForegroundColor Cyan
    Write-Host ""
    $apiKey = Read-Host "  Paste your ANTHROPIC_API_KEY (sk-ant-...)"
    $apiKey = $apiKey.Trim()
    if ($apiKey.Length -lt 20) {
        Write-Host "  ERROR: Key looks too short. Please check and re-run." -ForegroundColor Red
        Read-Host "Press Enter to exit"
        exit 1
    }
}

# Set for current session
$env:ANTHROPIC_API_KEY = $apiKey
[System.Environment]::SetEnvironmentVariable("ANTHROPIC_API_KEY", $apiKey, "User")
Write-Host "  OK -- API key set (saved to User environment variables)." -ForegroundColor Green

# ---- Step 3: Write .env file (for Docker mode) --------------------------------
Write-Host ""
Write-Host "[3/6] Writing .env file for Docker mode..." -ForegroundColor Yellow
$envContent = @"
# ADLC-Agent-Kit environment -- generated by authorize-agents.ps1
ANTHROPIC_API_KEY=$apiKey
CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1
COMPOSE_PROJECT_NAME=panchayat
"@
Set-Content -Path (Join-Path $ROOT ".env") -Value $envContent -Encoding UTF8
Write-Host "  OK -- .env written to $ROOT\.env" -ForegroundColor Green

# ---- Step 4: Write .claude\settings.json (pre-approve all tools) --------------
Write-Host ""
Write-Host "[4/6] Writing .claude\settings.json (pre-approving all tool permissions)..." -ForegroundColor Yellow
$claudeDir = Join-Path $ROOT ".claude"
if (-not (Test-Path $claudeDir)) { New-Item -ItemType Directory -Path $claudeDir | Out-Null }
$settingsJson = @'
{
  "permissions": {
    "allow": [
      "Bash(*)",
      "Read(*)",
      "Write(*)",
      "Edit(*)",
      "MultiEdit(*)",
      "Glob(*)",
      "Grep(*)",
      "LS(*)",
      "TodoWrite(*)",
      "TodoRead(*)",
      "WebFetch(*)",
      "WebSearch(*)"
    ],
    "deny": []
  },
  "env": {
    "CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS": "1"
  }
}
'@
Set-Content -Path (Join-Path $claudeDir "settings.json") -Value $settingsJson -Encoding UTF8
Write-Host "  OK -- .claude\settings.json written." -ForegroundColor Green

# ---- Step 5: Run 'claude auth' to authenticate CLI ---------------------------
Write-Host ""
Write-Host "[5/6] Authenticating claude CLI against Anthropic API..." -ForegroundColor Yellow
Write-Host "  Running: claude --version" -ForegroundColor DarkGray
$version = & claude --version 2>&1
Write-Host "  $version" -ForegroundColor DarkGray

# Test API key is accepted
Write-Host "  Testing API key with a quick ping..." -ForegroundColor DarkGray
$testResult = & claude --print "Reply with just the word AUTHORIZED" --dangerously-skip-permissions 2>&1
if ($testResult -match "AUTHORIZED") {
    Write-Host "  OK -- API key accepted. Claude responded: $testResult" -ForegroundColor Green
} elseif ($testResult -match "error|invalid|401|403" -or $testResult -match "authentication") {
    Write-Host ""
    Write-Host "  ERROR: API key rejected by Anthropic." -ForegroundColor Red
    Write-Host "  Response: $testResult" -ForegroundColor DarkGray
    Write-Host "  Check your key at https://console.anthropic.com/ and re-run." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
} else {
    Write-Host "  OK -- Claude responded (key appears valid)." -ForegroundColor Green
    Write-Host "  Response: $testResult" -ForegroundColor DarkGray
}

# ---- Step 6: Verify prompt files present ------------------------------------
Write-Host ""
Write-Host "[6/6] Verifying agent prompt files..." -ForegroundColor Yellow
$agents = @("arjun", "vikram", "rasool", "kavya", "kiran", "rohan", "keerthi")
$allOk = $true
foreach ($agent in $agents) {
    $pFile = Join-Path $ROOT "prompts\$agent-prompt.txt"
    if (Test-Path $pFile) {
        $lines = (Get-Content $pFile).Count
        Write-Host "  OK  prompts\$agent-prompt.txt ($lines lines)" -ForegroundColor Green
    } else {
        Write-Host "  MISSING  prompts\$agent-prompt.txt" -ForegroundColor Red
        $allOk = $false
    }
}
if (-not $allOk) {
    Write-Host ""
    Write-Host "  WARNING: Some prompt files are missing." -ForegroundColor Yellow
    Write-Host "  Agents without a prompt file will need prompts pasted manually." -ForegroundColor Gray
}

# ---- Summary -----------------------------------------------------------------
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  AUTHORIZATION COMPLETE" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  API key   : set in User environment (persists after reboot)" -ForegroundColor White
Write-Host "  .env      : written (Docker / Compose mode)" -ForegroundColor White
Write-Host "  Permissions: all tools pre-approved in .claude\settings.json" -ForegroundColor White
Write-Host "  Agents    : will run WITHOUT permission prompts" -ForegroundColor White
Write-Host ""
Write-Host "  NEXT STEPS:" -ForegroundColor Cyan
Write-Host "  -- Standard mode  : .\start-agents.ps1" -ForegroundColor Yellow
Write-Host "  -- Auto-run mode  : .\start-agents.ps1 -AutoRun" -ForegroundColor Yellow
Write-Host "  -- Docker mode    : .\docker-start.ps1" -ForegroundColor Yellow
Write-Host ""
Read-Host "Press Enter to close"
