# Agent: kiran | Sprint: 01 | Date: 2026-03-16
"""IacTemplate ORM model — Claude-generated Terraform code artefacts."""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class IacTemplate(Base):
    """
    Versioned Terraform code artefacts generated by Claude.

    template_type values:
      'terraform'     — full generated Terraform output (multi-file JSON)
      'canvas_state'  — serialised React Flow canvas nodes + edges
    """

    __tablename__ = "iac_templates"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    template_type: Mapped[str] = mapped_column(
        String(32), default="terraform", nullable=False
    )
    content: Mapped[str] = mapped_column(Text, nullable=False)
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    language: Mapped[str] = mapped_column(String(32), default="hcl", nullable=False)
    created_by_llm: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    llm_session_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    project: Mapped["Project"] = relationship(  # noqa: F821
        "Project", back_populates="iac_templates", lazy="select"
    )
